/**
 * AI Insights Service
 * Integrates with Google's Gemini API (free tier) to generate dashboard insights
 */

interface DashboardData {
  visualizations: Array<{
    id: string;
    title: string;
    type: string;
    data: any[];
  }>;
  metadata: {
    totalVisualizations: number;
    dashboardTitle?: string;
    dateRange?: string;
    analysisType?: string;
    focusAreas?: string[];
  };
}

interface AIInsight {
  id: string;
  type: "trend" | "comparison" | "outlier" | "summary" | "recommendation";
  title: string;
  description: string;
  value?: string | number;
  confidence: "high" | "medium" | "low";
  recommendation?: string;
  priority: "high" | "medium" | "low";
}

class AIInsightsService {
  private apiKey: string | null = null;
  private baseUrl = 'https://generativelanguage.googleapis.com/v1beta/models/gemini-pro:generateContent';

  constructor() {
    // Try to get API key from environment variables
    // In browser environment, process.env might not be available
    try {
      this.apiKey = (typeof process !== 'undefined' && process.env) ? process.env.REACT_APP_GEMINI_API_KEY || null : null;
    } catch (error) {
      this.apiKey = null;
    }
  }

  /**
   * Set API key manually if not available in environment
   */
  setApiKey(apiKey: string) {
    this.apiKey = apiKey;
  }

  /**
   * Check if AI service is available
   */
  isAvailable(): boolean {
    return this.apiKey !== null;
  }

  /**
   * Generate insights using AI
   */
  async generateInsights(dashboardData: DashboardData): Promise<AIInsight[]> {
    if (!this.apiKey) {
      console.warn('AI Insights: No API key available, falling back to local analysis');
      return this.generateFallbackInsights(dashboardData);
    }

    try {
      const prompt = this.constructPrompt(dashboardData);
      
      const response = await fetch(`${this.baseUrl}?key=${this.apiKey}`, {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({
          contents: [{
            parts: [{
              text: prompt
            }]
          }],
          generationConfig: {
            temperature: 0.7,
            topK: 40,
            topP: 0.95,
            maxOutputTokens: 2048,
          }
        })
      });

      if (!response.ok) {
        throw new Error(`AI API Error: ${response.status}`);
      }

      const data = await response.json();
      const generatedText = data.candidates?.[0]?.content?.parts?.[0]?.text;
      
      if (!generatedText) {
        throw new Error('No insights generated by AI');
      }

      return this.parseAIResponse(generatedText);

    } catch (error) {
      console.warn('AI Insights generation failed:', error);
      return this.generateFallbackInsights(dashboardData);
    }
  }

  /**
   * Construct prompt for AI based on dashboard data
   */
  private constructPrompt(dashboardData: DashboardData): string {
    const { visualizations, metadata } = dashboardData;
    
    let prompt = `Analyze this comprehensive dashboard data and provide 6-10 actionable insights by finding relationships and patterns ACROSS visualizations. Look for connections between different charts and metrics.

Dashboard: ${metadata.dashboardTitle || 'Analytics Dashboard'}
Total Visualizations: ${metadata.totalVisualizations}
${metadata.dateRange ? `Date Range: ${metadata.dateRange}` : ''}

CROSS-VISUALIZATION ANALYSIS REQUIRED:
`;

    // Add detailed data for cross-analysis
    visualizations.forEach((viz, index) => {
      prompt += `
${index + 1}. ${viz.title} (${viz.type})
   Data Summary: ${this.summarizeVisualizationData(viz.data)}
   Full Data Structure: ${this.getDetailedDataStructure(viz.data)}
`;
    });

    // Add relationship analysis instructions
    prompt += `

CRITICAL: Perform CROSS-VISUALIZATION ANALYSIS to find:
1. **Gender/Demographic Patterns**: If you see male/female data across charts, compare enrollment rates, performance gaps, trends
2. **Geographic Correlations**: Compare performance between regions/districts across different metrics
3. **Time-based Relationships**: Identify trends that appear across multiple visualizations
4. **Performance Correlations**: Link high/low performers across different indicators
5. **Resource-Outcome Relationships**: Connect infrastructure/resource data with performance outcomes
6. **Efficiency Patterns**: Compare input metrics (teachers, funding) with output metrics (enrollment, grades)

EXAMPLES OF CROSS-ANALYSIS INSIGHTS:
- "Districts with higher teacher-student ratios show 15% better learning outcomes"
- "Female enrollment dropped 8% in regions where infrastructure scores are below 60%"
- "Primary completion rates correlate strongly with handwashing facility availability (R=0.73)"

Please provide insights in this exact JSON format:
[
  {
    "id": "cross_analysis_1",
    "type": "comparison|trend|outlier|summary|recommendation",
    "title": "Cross-metric insight title",
    "description": "Detailed explanation showing relationships between 2+ visualizations with specific data points",
    "value": "key correlation coefficient, percentage difference, or comparative metric",
    "confidence": "high|medium|low",
    "recommendation": "Specific actionable recommendation based on the cross-analysis",
    "priority": "high|medium|low"
  }
]

MANDATORY REQUIREMENTS:
- Each insight MUST reference data from at least 2 different visualizations
- Include specific numbers, percentages, and comparisons
- Identify cause-effect relationships where possible
- Highlight unexpected correlations or patterns
- Provide actionable recommendations based on cross-metric analysis
- Use terms like "compared to", "correlation with", "in relation to", "while X shows Y"

Focus on finding hidden patterns that only become visible when analyzing multiple charts together!`;

    return prompt;
  }

  /**
   * Summarize visualization data for the prompt
   */
  private summarizeVisualizationData(data: any[]): string {
    if (!data || data.length === 0) return "No data available";
    
    const sample = data.slice(0, 5); // First 5 items
    const summary = sample.map(item => {
      const keys = Object.keys(item);
      
      // Try to find common value and label fields
      const valueKey = keys.find(k => 
        ['value', 'Value', 'count', 'total', 'amount', 'sum'].includes(k)
      ) || keys.find(k => typeof item[k] === 'number') || keys[0];
      
      const labelKey = keys.find(k => 
        ['name', 'label', 'category', 'orgUnit', 'dataElement', 'period', 'indicator'].includes(k)
      ) || keys.find(k => typeof item[k] === 'string' && k !== valueKey) || keys[1];
      
      const value = item[valueKey];
      const label = item[labelKey];
      
      // Format the value if it's a number
      const formattedValue = typeof value === 'number' ? 
        (value > 1000 ? `${(value/1000).toFixed(1)}K` : value.toString()) : 
        (value || 'N/A');
      
      return `${label || 'Item'}: ${formattedValue}`;
    }).join(', ');
    
    // Add some basic statistics
    const numericValues = data
      .map(item => {
        const keys = Object.keys(item);
        const valueKey = keys.find(k => typeof item[k] === 'number');
        return valueKey ? item[valueKey] : null;
      })
      .filter(v => v !== null && !isNaN(v));
      
    if (numericValues.length > 0) {
      const total = numericValues.reduce((sum, val) => sum + val, 0);
      const avg = total / numericValues.length;
      const max = Math.max(...numericValues);
      const min = Math.min(...numericValues);
      
      return `${summary}${data.length > 5 ? ` ... and ${data.length - 5} more items` : ''}. Stats: Total=${total > 1000 ? `${(total/1000).toFixed(1)}K` : total}, Avg=${avg.toFixed(1)}, Range=${min}-${max}`;
    }
    
    return `${summary}${data.length > 5 ? ` ... and ${data.length - 5} more items` : ''}`;
  }

  /**
   * Get detailed data structure for comprehensive analysis
   */
  private getDetailedDataStructure(data: any[]): string {
    if (!data || data.length === 0) return "No detailed data available";
    
    // Take a larger sample for cross-analysis
    const sample = data.slice(0, 10);
    const fieldAnalysis: { [key: string]: any } = {};
    
    // Analyze all fields across the sample
    sample.forEach(item => {
      Object.keys(item).forEach(key => {
        if (!fieldAnalysis[key]) {
          fieldAnalysis[key] = {
            type: typeof item[key],
            values: new Set(),
            isNumeric: typeof item[key] === 'number',
            hasGender: false,
            hasLocation: false,
            hasPeriod: false
          };
        }
        
        fieldAnalysis[key].values.add(item[key]);
        
        // Check for gender-related fields
        if (typeof item[key] === 'string') {
          const value = item[key].toLowerCase();
          if (value.includes('male') || value.includes('female') || value.includes('boys') || value.includes('girls')) {
            fieldAnalysis[key].hasGender = true;
          }
          
          // Check for location fields
          if (value.includes('district') || value.includes('region') || value.includes('zone') || key.toLowerCase().includes('orgunit')) {
            fieldAnalysis[key].hasLocation = true;
          }
          
          // Check for period/time fields
          if (value.match(/\d{4}/) || value.includes('quarter') || value.includes('month') || key.toLowerCase().includes('period')) {
            fieldAnalysis[key].hasPeriod = true;
          }
        }
      });
    });
    
    // Create structured summary
    let structure = "Key Data Fields: ";
    const importantFields = Object.entries(fieldAnalysis)
      .filter(([_, analysis]) => analysis.hasGender || analysis.hasLocation || analysis.hasPeriod || analysis.isNumeric)
      .map(([field, analysis]) => {
        const tags = [];
        if (analysis.hasGender) tags.push("GENDER");
        if (analysis.hasLocation) tags.push("LOCATION");  
        if (analysis.hasPeriod) tags.push("TIME");
        if (analysis.isNumeric) tags.push("NUMERIC");
        
        const uniqueValues = Math.min(analysis.values.size, 5);
        return `${field}[${tags.join(',')}]: ${uniqueValues} unique values`;
      })
      .join(', ');
    
    structure += importantFields || "Standard data fields";
    
    // Add sample records for pattern recognition
    if (sample.length > 0) {
      structure += `. Sample records: `;
      structure += sample.slice(0, 3).map(record => {
        const keyFields = Object.entries(record)
          .filter(([key, value]) => 
            key.toLowerCase().includes('male') || 
            key.toLowerCase().includes('female') ||
            key.toLowerCase().includes('district') ||
            key.toLowerCase().includes('region') ||
            typeof value === 'number'
          )
          .map(([key, value]) => `${key}:${value}`)
          .join(',');
        return `{${keyFields}}`;
      }).join(' | ');
    }
    
    return structure;
  }

  /**
   * Parse AI response to extract insights
   */
  private parseAIResponse(response: string): AIInsight[] {
    try {
      // Extract JSON from response (AI might include extra text)
      const jsonMatch = response.match(/\[[\s\S]*\]/);
      if (!jsonMatch) {
        throw new Error('No JSON found in AI response');
      }

      const insights = JSON.parse(jsonMatch[0]);
      
      // Validate and clean insights
      return insights
        .filter((insight: any) => insight.title && insight.description)
        .map((insight: any, index: number) => ({
          id: insight.id || `ai_insight_${Date.now()}_${index}`,
          type: insight.type || 'summary',
          title: insight.title,
          description: insight.description,
          value: insight.value,
          confidence: insight.confidence || 'medium',
          recommendation: insight.recommendation,
          priority: insight.priority || 'medium'
        }))
        .slice(0, 8); // Limit to 8 insights

    } catch (error) {
      console.warn('Failed to parse AI response:', error);
      return [];
    }
  }

  /**
   * Fallback insights when AI is not available
   */
  private generateFallbackInsights(dashboardData: DashboardData): AIInsight[] {
    const { visualizations, metadata } = dashboardData;
    
    return [
      {
        id: 'fallback_1',
        type: 'summary',
        title: 'Dashboard Overview',
        description: `This dashboard contains ${metadata.totalVisualizations} visualizations providing insights into your data.`,
        confidence: 'high',
        recommendation: 'Consider connecting to an AI service for more detailed insights.',
        priority: 'low'
      },
      ...visualizations.slice(0, 3).map((viz, index) => ({
        id: `fallback_viz_${index}`,
        type: 'summary' as const,
        title: `${viz.title} Analysis`,
        description: `${viz.title} shows ${viz.data?.length || 0} data points. This ${viz.type} visualization provides valuable insights into your metrics.`,
        value: viz.data?.length?.toString(),
        confidence: 'medium' as const,
        recommendation: 'Review the data trends and consider additional analysis.',
        priority: 'medium' as const
      }))
    ];
  }
}

export default new AIInsightsService();
export type { AIInsight, DashboardData };