/**
 * AI Insights Service
 * Integrates with Google's Gemini API (free tier) to generate dashboard insights
 */

interface DashboardData {
  visualizations: Array<{
    id: string;
    title: string;
    type: string;
    data: any[];
  }>;
  metadata: {
    totalVisualizations: number;
    dashboardTitle?: string;
    dateRange?: string;
    analysisType?: string;
    focusAreas?: string[];
  };
}

interface AIInsight {
  id: string;
  type: "trend" | "comparison" | "outlier" | "summary" | "recommendation";
  title: string;
  description: string;
  value?: string | number;
  confidence: "high" | "medium" | "low";
  recommendation?: string;
  priority: "high" | "medium" | "low";
}

class AIInsightsService {
  private apiKey: string | null = null;
  private baseUrl = 'https://generativelanguage.googleapis.com/v1beta/models/gemini-pro:generateContent';

  constructor() {
    // Try to get API key from environment variables
    // In browser environment, process.env might not be available
    try {
      this.apiKey = (typeof process !== 'undefined' && process.env) ? process.env.REACT_APP_GEMINI_API_KEY || null : null;
    } catch (error) {
      this.apiKey = null;
    }
  }

  /**
   * Set API key manually if not available in environment
   */
  setApiKey(apiKey: string) {
    this.apiKey = apiKey;
  }

  /**
   * Check if AI service is available
   */
  isAvailable(): boolean {
    return this.apiKey !== null;
  }

  /**
   * Generate insights using AI
   */
  async generateInsights(dashboardData: DashboardData): Promise<AIInsight[]> {
    if (!this.apiKey) {
      console.warn('AI Insights: No API key available, falling back to local analysis');
      return this.generateFallbackInsights(dashboardData);
    }

    try {
      const prompt = this.constructPrompt(dashboardData);
      
      const response = await fetch(`${this.baseUrl}?key=${this.apiKey}`, {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({
          contents: [{
            parts: [{
              text: prompt
            }]
          }],
          generationConfig: {
            temperature: 0.7,
            topK: 40,
            topP: 0.95,
            maxOutputTokens: 2048,
          }
        })
      });

      if (!response.ok) {
        throw new Error(`AI API Error: ${response.status}`);
      }

      const data = await response.json();
      const generatedText = data.candidates?.[0]?.content?.parts?.[0]?.text;
      
      if (!generatedText) {
        throw new Error('No insights generated by AI');
      }

      return this.parseAIResponse(generatedText);

    } catch (error) {
      console.warn('AI Insights generation failed:', error);
      return this.generateFallbackInsights(dashboardData);
    }
  }

  /**
   * Construct prompt for AI based on dashboard data
   */
  private constructPrompt(dashboardData: DashboardData): string {
    const { visualizations, metadata } = dashboardData;
    
    let prompt = `Analyze this comprehensive dashboard data and provide 6-10 specific, detailed insights with real numbers and concrete analysis. DO NOT describe "data points" - analyze the actual patterns and relationships in the data.

Dashboard: ${metadata.dashboardTitle || 'Analytics Dashboard'}
Total Visualizations: ${metadata.totalVisualizations}
${metadata.dateRange ? `Date Range: ${metadata.dateRange}` : ''}

GENERATE DETAILED INSIGHTS LIKE THIS EXAMPLE:
"Boys outnumber girls in every region, with the gap widest in Lubombo (about 2,160) and narrowest in Shiselweni (about 1,524). Manzini leads in total enrollment (35,228 boys vs. 33,257 girls) while Shiselweni trails (24,967 vs. 23,443). Lubombo's roughly 9% gap stands out. Targeted girls' outreach there—and improving overall access in Shiselweni—could have the biggest impact."

CROSS-VISUALIZATION ANALYSIS REQUIRED:
`;

    // Add detailed data for cross-analysis
    visualizations.forEach((viz, index) => {
      prompt += `
${index + 1}. ${viz.title} (${viz.type})
   Data Summary: ${this.summarizeVisualizationData(viz.data)}
   Full Data Structure: ${this.getDetailedDataStructure(viz.data)}
`;
    });

    // Add relationship analysis instructions
    prompt += `

CRITICAL: Perform CROSS-VISUALIZATION ANALYSIS to find:
1. **Gender/Demographic Patterns**: If you see male/female data across charts, compare enrollment rates, performance gaps, trends
2. **Geographic Correlations**: Compare performance between regions/districts across different metrics
3. **Time-based Relationships**: Identify trends that appear across multiple visualizations
4. **Performance Correlations**: Link high/low performers across different indicators
5. **Resource-Outcome Relationships**: Connect infrastructure/resource data with performance outcomes
6. **Efficiency Patterns**: Compare input metrics (teachers, funding) with output metrics (enrollment, grades)

EXAMPLES OF CROSS-ANALYSIS INSIGHTS:
- "Districts with higher teacher-student ratios show 15% better learning outcomes"
- "Female enrollment dropped 8% in regions where infrastructure scores are below 60%"
- "Primary completion rates correlate strongly with handwashing facility availability (R=0.73)"

Please provide insights in this exact JSON format:
[
  {
    "id": "cross_analysis_1",
    "type": "comparison|trend|outlier|summary|recommendation",
    "title": "Cross-metric insight title",
    "description": "Detailed explanation showing relationships between 2+ visualizations with specific data points",
    "value": "key correlation coefficient, percentage difference, or comparative metric",
    "confidence": "high|medium|low",
    "recommendation": "Specific actionable recommendation based on the cross-analysis",
    "priority": "high|medium|low"
  }
]

MANDATORY REQUIREMENTS:
- Each insight MUST reference data from at least 2 different visualizations
- Include specific numbers, percentages, and comparisons (like "35,228 boys vs. 33,257 girls")
- NO generic descriptions like "shows X data points" - analyze actual patterns
- Identify cause-effect relationships where possible
- Highlight unexpected correlations or patterns
- Provide actionable recommendations based on cross-metric analysis
- Use terms like "compared to", "correlation with", "in relation to", "while X shows Y"
- Write insights like a data analyst would - specific, detailed, actionable

EXAMPLES OF GOOD INSIGHTS:
- "District A leads with 15,420 students while District B trails with 8,340 - a 85% difference"
- "Female completion rates drop 12% in areas where infrastructure scores fall below 60%"
- "Schools with teacher-student ratios above 1:30 show 18% lower test scores across all subjects"

Focus on finding hidden patterns that only become visible when analyzing multiple charts together!`;

    return prompt;
  }

  /**
   * Summarize visualization data for the prompt
   */
  private summarizeVisualizationData(data: any[]): string {
    if (!data || data.length === 0) return "No data available";
    
    const sample = data.slice(0, 5); // First 5 items
    const summary = sample.map(item => {
      const keys = Object.keys(item);
      
      // Try to find common value and label fields
      const valueKey = keys.find(k => 
        ['value', 'Value', 'count', 'total', 'amount', 'sum'].includes(k)
      ) || keys.find(k => typeof item[k] === 'number') || keys[0];
      
      const labelKey = keys.find(k => 
        ['name', 'label', 'category', 'orgUnit', 'dataElement', 'period', 'indicator'].includes(k)
      ) || keys.find(k => typeof item[k] === 'string' && k !== valueKey) || keys[1];
      
      const value = item[valueKey];
      const label = item[labelKey];
      
      // Format the value if it's a number
      const formattedValue = typeof value === 'number' ? 
        (value > 1000 ? `${(value/1000).toFixed(1)}K` : value.toString()) : 
        (value || 'N/A');
      
      return `${label || 'Item'}: ${formattedValue}`;
    }).join(', ');
    
    // Add some basic statistics
    const numericValues = data
      .map(item => {
        const keys = Object.keys(item);
        const valueKey = keys.find(k => typeof item[k] === 'number');
        return valueKey ? item[valueKey] : null;
      })
      .filter(v => v !== null && !isNaN(v));
      
    if (numericValues.length > 0) {
      const total = numericValues.reduce((sum, val) => sum + val, 0);
      const avg = total / numericValues.length;
      const max = Math.max(...numericValues);
      const min = Math.min(...numericValues);
      
      return `${summary}${data.length > 5 ? ` ... and ${data.length - 5} more items` : ''}. Stats: Total=${total > 1000 ? `${(total/1000).toFixed(1)}K` : total}, Avg=${avg.toFixed(1)}, Range=${min}-${max}`;
    }
    
    return `${summary}${data.length > 5 ? ` ... and ${data.length - 5} more items` : ''}`;
  }

  /**
   * Get detailed data structure for comprehensive analysis
   */
  private getDetailedDataStructure(data: any[]): string {
    if (!data || data.length === 0) return "No detailed data available";
    
    // Take a larger sample for cross-analysis
    const sample = data.slice(0, 10);
    const fieldAnalysis: { [key: string]: any } = {};
    
    // Analyze all fields across the sample
    sample.forEach(item => {
      Object.keys(item).forEach(key => {
        if (!fieldAnalysis[key]) {
          fieldAnalysis[key] = {
            type: typeof item[key],
            values: new Set(),
            isNumeric: typeof item[key] === 'number',
            hasGender: false,
            hasLocation: false,
            hasPeriod: false
          };
        }
        
        fieldAnalysis[key].values.add(item[key]);
        
        // Check for gender-related fields
        if (typeof item[key] === 'string') {
          const value = item[key].toLowerCase();
          if (value.includes('male') || value.includes('female') || value.includes('boys') || value.includes('girls')) {
            fieldAnalysis[key].hasGender = true;
          }
          
          // Check for location fields
          if (value.includes('district') || value.includes('region') || value.includes('zone') || key.toLowerCase().includes('orgunit')) {
            fieldAnalysis[key].hasLocation = true;
          }
          
          // Check for period/time fields
          if (value.match(/\d{4}/) || value.includes('quarter') || value.includes('month') || key.toLowerCase().includes('period')) {
            fieldAnalysis[key].hasPeriod = true;
          }
        }
      });
    });
    
    // Create structured summary
    let structure = "Key Data Fields: ";
    const importantFields = Object.entries(fieldAnalysis)
      .filter(([_, analysis]) => analysis.hasGender || analysis.hasLocation || analysis.hasPeriod || analysis.isNumeric)
      .map(([field, analysis]) => {
        const tags = [];
        if (analysis.hasGender) tags.push("GENDER");
        if (analysis.hasLocation) tags.push("LOCATION");  
        if (analysis.hasPeriod) tags.push("TIME");
        if (analysis.isNumeric) tags.push("NUMERIC");
        
        const uniqueValues = Math.min(analysis.values.size, 5);
        return `${field}[${tags.join(',')}]: ${uniqueValues} unique values`;
      })
      .join(', ');
    
    structure += importantFields || "Standard data fields";
    
    // Add sample records for pattern recognition
    if (sample.length > 0) {
      structure += `. Sample records: `;
      structure += sample.slice(0, 3).map(record => {
        const keyFields = Object.entries(record)
          .filter(([key, value]) => 
            key.toLowerCase().includes('male') || 
            key.toLowerCase().includes('female') ||
            key.toLowerCase().includes('district') ||
            key.toLowerCase().includes('region') ||
            typeof value === 'number'
          )
          .map(([key, value]) => `${key}:${value}`)
          .join(',');
        return `{${keyFields}}`;
      }).join(' | ');
    }
    
    return structure;
  }

  /**
   * Parse AI response to extract insights
   */
  private parseAIResponse(response: string): AIInsight[] {
    try {
      // Extract JSON from response (AI might include extra text)
      const jsonMatch = response.match(/\[[\s\S]*\]/);
      if (!jsonMatch) {
        throw new Error('No JSON found in AI response');
      }

      const insights = JSON.parse(jsonMatch[0]);
      
      // Validate and clean insights
      return insights
        .filter((insight: any) => insight.title && insight.description)
        .map((insight: any, index: number) => ({
          id: insight.id || `ai_insight_${Date.now()}_${index}`,
          type: insight.type || 'summary',
          title: insight.title,
          description: insight.description,
          value: insight.value,
          confidence: insight.confidence || 'medium',
          recommendation: insight.recommendation,
          priority: insight.priority || 'medium'
        }))
        .slice(0, 8); // Limit to 8 insights

    } catch (error) {
      console.warn('Failed to parse AI response:', error);
      return [];
    }
  }

  /**
   * Fallback insights when AI is not available - analyze actual data patterns
   */
  private generateFallbackInsights(dashboardData: DashboardData): AIInsight[] {
    const { visualizations, metadata } = dashboardData;
    const insights: AIInsight[] = [];
    
    console.log('Generating fallback insights for', visualizations.length, 'visualizations');
    
    // Try to generate meaningful insights from actual data
    for (const viz of visualizations.slice(0, 5)) {
      console.log(`Analyzing viz: ${viz.title}, type: ${viz.type}, data length: ${viz.data?.length}`);
      
      if (viz.data && viz.data.length > 0) {
        console.log('Sample data:', viz.data.slice(0, 2));
      }
      
      const dataInsight = this.analyzeVisualizationData(viz);
      if (dataInsight) {
        console.log('Generated insight:', dataInsight.title);
        insights.push(dataInsight);
      }
    }
    
    // Generate basic insights even if detailed analysis fails
    if (insights.length === 0) {
      // Try to create at least some basic insights from the data
      const basicInsights = this.generateBasicInsights(visualizations);
      insights.push(...basicInsights);
    }
    
    // Final fallback if nothing works
    if (insights.length === 0) {
      insights.push({
        id: 'fallback_1',
        type: 'summary',
        title: 'Dashboard Ready for Analysis',
        description: `Dashboard contains ${metadata.totalVisualizations} visualizations with data ready for AI-powered insights.`,
        confidence: 'high',
        recommendation: 'Connect to AI service for detailed cross-visualization analysis.',
        priority: 'medium'
      });
    }
    
    console.log('Generated', insights.length, 'fallback insights');
    return insights;
  }
  
  /**
   * Generate basic insights when detailed analysis fails
   */
  private generateBasicInsights(visualizations: any[]): AIInsight[] {
    const insights: AIInsight[] = [];
    
    for (const viz of visualizations.slice(0, 3)) {
      if (!viz.data || viz.data.length === 0) continue;
      
      // Calculate basic statistics
      const numericData = viz.data.map((item: any) => {
        const numValue = Object.values(item).find(v => typeof v === 'number') as number;
        return numValue || 0;
      }).filter(val => val > 0);
      
      if (numericData.length > 0) {
        const total = numericData.reduce((sum, val) => sum + val, 0);
        const average = Math.round(total / numericData.length);
        const max = Math.max(...numericData);
        const min = Math.min(...numericData);
        
        insights.push({
          id: `basic_${viz.id}_${Date.now()}`,
          type: 'summary',
          title: `${viz.title} Summary`,
          description: `Total: ${total.toLocaleString()}, Average: ${average.toLocaleString()}, Range: ${min.toLocaleString()} to ${max.toLocaleString()}. Highest value is ${Math.round((max/total)*100)}% of total.`,
          value: total.toLocaleString(),
          confidence: 'medium',
          recommendation: 'Review high and low performers for optimization opportunities.',
          priority: 'medium'
        });
      }
    }
    
    return insights;
  }
  
  /**
   * Analyze individual visualization data to generate meaningful insights
   */
  private analyzeVisualizationData(viz: any): AIInsight | null {
    if (!viz.data || viz.data.length === 0) return null;
    
    try {
      // Look for gender-related patterns
      const genderInsight = this.findGenderPatterns(viz);
      if (genderInsight) return genderInsight;
      
      // Look for geographic patterns
      const geoInsight = this.findGeographicPatterns(viz);
      if (geoInsight) return geoInsight;
      
      // Look for performance patterns
      const performanceInsight = this.findPerformancePatterns(viz);
      if (performanceInsight) return performanceInsight;
      
      return null;
    } catch (error) {
      return null;
    }
  }
  
  /**
   * Find gender-related patterns in data
   */
  private findGenderPatterns(viz: any): AIInsight | null {
    const data = viz.data;
    
    console.log('Looking for gender patterns in', viz.title);
    
    // Look for male/female data - check all fields
    const genderData = data.filter((item: any) => {
      const allText = JSON.stringify(item).toLowerCase();
      const hasGender = allText.includes('male') || allText.includes('female') || 
                       allText.includes('boys') || allText.includes('girls') ||
                       allText.includes('men') || allText.includes('women');
      
      if (hasGender) {
        console.log('Found gender data:', item);
      }
      
      return hasGender;
    });
    
    if (genderData.length > 1) {
      // Find regions/locations
      const regions = [...new Set(genderData.map((item: any) => 
        item.orgUnit || item.region || item.location || item.name || 'Unknown'
      ))];
      
      if (regions.length > 1) {
        // Calculate gender gaps
        const gaps = regions.map(region => {
          const regionData = genderData.filter((item: any) => 
            (item.orgUnit || item.region || item.location || item.name) === region
          );
          
          const maleValues = regionData.filter((item: any) => {
            const str = JSON.stringify(item).toLowerCase();
            return str.includes('male') && !str.includes('female');
          });
          
          const femaleValues = regionData.filter((item: any) => {
            const str = JSON.stringify(item).toLowerCase();
            return str.includes('female');
          });
          
          const maleTotal = maleValues.reduce((sum: number, item: any) => {
            const numValue = Object.values(item).find(v => typeof v === 'number');
            return sum + (numValue as number || 0);
          }, 0);
          
          const femaleTotal = femaleValues.reduce((sum: number, item: any) => {
            const numValue = Object.values(item).find(v => typeof v === 'number');
            return sum + (numValue as number || 0);
          }, 0);
          
          return {
            region,
            male: maleTotal,
            female: femaleTotal,
            gap: maleTotal - femaleTotal,
            total: maleTotal + femaleTotal
          };
        }).filter(gap => gap.male > 0 || gap.female > 0);
        
        if (gaps.length > 1) {
          const maxGap = gaps.reduce((max, current) => 
            Math.abs(current.gap) > Math.abs(max.gap) ? current : max
          );
          const minGap = gaps.reduce((min, current) => 
            Math.abs(current.gap) < Math.abs(min.gap) ? current : min
          );
          
          const highestTotal = gaps.reduce((max, current) => 
            current.total > max.total ? current : max
          );
          
          const gapDirection = maxGap.gap > 0 ? 'boys outnumber girls' : 'girls outnumber boys';
          const gapPercentage = Math.round((Math.abs(maxGap.gap) / maxGap.total) * 100);
          
          return {
            id: `gender_analysis_${Date.now()}`,
            type: 'comparison',
            title: 'Gender Enrollment Patterns by Region',
            description: `${gapDirection.charAt(0).toUpperCase() + gapDirection.slice(1)} in every region, with the gap widest in ${maxGap.region} (about ${Math.abs(maxGap.gap).toLocaleString()}) and narrowest in ${minGap.region} (about ${Math.abs(minGap.gap).toLocaleString()}). ${highestTotal.region} leads in total enrollment (${highestTotal.male.toLocaleString()} vs. ${highestTotal.female.toLocaleString()}) while other regions trail. ${maxGap.region}'s roughly ${gapPercentage}% gap stands out.`,
            value: `${gapPercentage}% gender gap`,
            confidence: 'high',
            recommendation: `Targeted ${maxGap.gap > 0 ? 'girls' : 'boys'} outreach in ${maxGap.region} and improving overall access in lower-performing regions could have the biggest impact.`,
            priority: 'high'
          };
        }
      }
    }
    
    return null;
  }
  
  /**
   * Find geographic patterns in data
   */
  private findGeographicPatterns(viz: any): AIInsight | null {
    const data = viz.data;
    
    // Look for location-based data
    const locationData = data.filter((item: any) => 
      item.orgUnit || item.region || item.location || item.district
    );
    
    if (locationData.length > 2) {
      const locationStats = locationData.map((item: any) => {
        const location = item.orgUnit || item.region || item.location || item.district || item.name;
        const value = Object.values(item).find(v => typeof v === 'number') as number || 0;
        
        return { location, value };
      }).filter(stat => stat.value > 0);
      
      if (locationStats.length > 2) {
        locationStats.sort((a, b) => b.value - a.value);
        
        const highest = locationStats[0];
        const lowest = locationStats[locationStats.length - 1];
        const average = locationStats.reduce((sum, stat) => sum + stat.value, 0) / locationStats.length;
        const gap = ((highest.value - lowest.value) / lowest.value) * 100;
        
        return {
          id: `geographic_analysis_${Date.now()}`,
          type: 'comparison',
          title: 'Regional Performance Variation',
          description: `${highest.location} leads with ${highest.value.toLocaleString()}, while ${lowest.location} records ${lowest.value.toLocaleString()} - a ${Math.round(gap)}% difference. The average across all regions is ${Math.round(average).toLocaleString()}, with ${locationStats.filter(s => s.value > average).length} regions above average.`,
          value: `${Math.round(gap)}% variation`,
          confidence: 'high',
          recommendation: `Focus resources on improving performance in ${lowest.location} and scaling successful practices from ${highest.location}.`,
          priority: 'high'
        };
      }
    }
    
    return null;
  }
  
  /**
   * Find performance patterns in data
   */
  private findPerformancePatterns(viz: any): AIInsight | null {
    const data = viz.data;
    
    if (data.length > 3) {
      const numericValues = data.map((item: any) => {
        const value = Object.values(item).find(v => typeof v === 'number') as number;
        const label = item.name || item.label || item.orgUnit || 'Item';
        return { label, value };
      }).filter(item => item.value > 0);
      
      if (numericValues.length > 3) {
        numericValues.sort((a, b) => b.value - a.value);
        
        const total = numericValues.reduce((sum, item) => sum + item.value, 0);
        const average = total / numericValues.length;
        const highest = numericValues[0];
        const lowest = numericValues[numericValues.length - 1];
        
        const topPerformers = numericValues.filter(item => item.value > average * 1.2);
        const underPerformers = numericValues.filter(item => item.value < average * 0.8);
        
        return {
          id: `performance_analysis_${Date.now()}`,
          type: 'summary',
          title: `${viz.title} Performance Overview`,
          description: `Total of ${total.toLocaleString()} across ${numericValues.length} categories. ${highest.label} leads with ${highest.value.toLocaleString()} (${Math.round((highest.value/total)*100)}% of total), while ${lowest.label} has ${lowest.value.toLocaleString()}. ${topPerformers.length} categories exceed 120% of average performance.`,
          value: `${topPerformers.length} top performers`,
          confidence: 'medium',
          recommendation: underPerformers.length > 0 ? 
            `Investigate success factors from ${highest.label} and apply to underperforming areas like ${underPerformers[0]?.label}.` :
            `Maintain current performance levels and consider scaling successful practices.`,
          priority: 'medium'
        };
      }
    }
    
    return null;
  }
}

export default new AIInsightsService();
export type { AIInsight, DashboardData };