/**
 * AI Insights Service
 * Integrates with Google's Gemini API (free tier) to generate dashboard insights
 */

interface DashboardData {
  visualizations: Array<{
    id: string;
    title: string;
    type: string;
    data: any[];
  }>;
  metadata: {
    totalVisualizations: number;
    dashboardTitle?: string;
    dateRange?: string;
  };
}

interface AIInsight {
  id: string;
  type: "trend" | "comparison" | "outlier" | "summary" | "recommendation";
  title: string;
  description: string;
  value?: string | number;
  confidence: "high" | "medium" | "low";
  recommendation?: string;
  priority: "high" | "medium" | "low";
}

class AIInsightsService {
  private apiKey: string | null = null;
  private baseUrl = 'https://generativelanguage.googleapis.com/v1beta/models/gemini-pro:generateContent';

  constructor() {
    // Try to get API key from environment variables
    // In browser environment, process.env might not be available
    try {
      this.apiKey = (typeof process !== 'undefined' && process.env) ? process.env.REACT_APP_GEMINI_API_KEY || null : null;
    } catch (error) {
      this.apiKey = null;
    }
  }

  /**
   * Set API key manually if not available in environment
   */
  setApiKey(apiKey: string) {
    this.apiKey = apiKey;
  }

  /**
   * Check if AI service is available
   */
  isAvailable(): boolean {
    return this.apiKey !== null;
  }

  /**
   * Generate insights using AI
   */
  async generateInsights(dashboardData: DashboardData): Promise<AIInsight[]> {
    if (!this.apiKey) {
      console.warn('AI Insights: No API key available, falling back to local analysis');
      return this.generateFallbackInsights(dashboardData);
    }

    try {
      const prompt = this.constructPrompt(dashboardData);
      
      const response = await fetch(`${this.baseUrl}?key=${this.apiKey}`, {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({
          contents: [{
            parts: [{
              text: prompt
            }]
          }],
          generationConfig: {
            temperature: 0.7,
            topK: 40,
            topP: 0.95,
            maxOutputTokens: 2048,
          }
        })
      });

      if (!response.ok) {
        throw new Error(`AI API Error: ${response.status}`);
      }

      const data = await response.json();
      const generatedText = data.candidates?.[0]?.content?.parts?.[0]?.text;
      
      if (!generatedText) {
        throw new Error('No insights generated by AI');
      }

      return this.parseAIResponse(generatedText);

    } catch (error) {
      console.warn('AI Insights generation failed:', error);
      return this.generateFallbackInsights(dashboardData);
    }
  }

  /**
   * Construct prompt for AI based on dashboard data
   */
  private constructPrompt(dashboardData: DashboardData): string {
    const { visualizations, metadata } = dashboardData;
    
    let prompt = `Analyze this dashboard data and provide 5-8 actionable insights and recommendations in JSON format.

Dashboard: ${metadata.dashboardTitle || 'Analytics Dashboard'}
Total Visualizations: ${metadata.totalVisualizations}
${metadata.dateRange ? `Date Range: ${metadata.dateRange}` : ''}

Visualization Data:
`;

    visualizations.forEach((viz, index) => {
      prompt += `
${index + 1}. ${viz.title} (${viz.type})
   Data Summary: ${this.summarizeVisualizationData(viz.data)}
`;
    });

    prompt += `

Please provide insights in this exact JSON format:
[
  {
    "id": "unique_id",
    "type": "trend|comparison|outlier|summary|recommendation",
    "title": "Brief insight title",
    "description": "Detailed explanation of the insight",
    "value": "key metric or percentage if applicable",
    "confidence": "high|medium|low",
    "recommendation": "Specific actionable recommendation",
    "priority": "high|medium|low"
  }
]

Focus on:
1. Key trends and patterns
2. Performance outliers (both positive and negative)
3. Comparative analysis between different metrics
4. Actionable recommendations for improvement
5. Data quality or completeness issues if any

Ensure insights are:
- Specific and actionable
- Based on the actual data provided
- Relevant to dashboard users
- Include concrete numbers where possible`;

    return prompt;
  }

  /**
   * Summarize visualization data for the prompt
   */
  private summarizeVisualizationData(data: any[]): string {
    if (!data || data.length === 0) return "No data available";
    
    const sample = data.slice(0, 5); // First 5 items
    const summary = sample.map(item => {
      const keys = Object.keys(item);
      
      // Try to find common value and label fields
      const valueKey = keys.find(k => 
        ['value', 'Value', 'count', 'total', 'amount', 'sum'].includes(k)
      ) || keys.find(k => typeof item[k] === 'number') || keys[0];
      
      const labelKey = keys.find(k => 
        ['name', 'label', 'category', 'orgUnit', 'dataElement', 'period', 'indicator'].includes(k)
      ) || keys.find(k => typeof item[k] === 'string' && k !== valueKey) || keys[1];
      
      const value = item[valueKey];
      const label = item[labelKey];
      
      // Format the value if it's a number
      const formattedValue = typeof value === 'number' ? 
        (value > 1000 ? `${(value/1000).toFixed(1)}K` : value.toString()) : 
        (value || 'N/A');
      
      return `${label || 'Item'}: ${formattedValue}`;
    }).join(', ');
    
    // Add some basic statistics
    const numericValues = data
      .map(item => {
        const keys = Object.keys(item);
        const valueKey = keys.find(k => typeof item[k] === 'number');
        return valueKey ? item[valueKey] : null;
      })
      .filter(v => v !== null && !isNaN(v));
      
    if (numericValues.length > 0) {
      const total = numericValues.reduce((sum, val) => sum + val, 0);
      const avg = total / numericValues.length;
      const max = Math.max(...numericValues);
      const min = Math.min(...numericValues);
      
      return `${summary}${data.length > 5 ? ` ... and ${data.length - 5} more items` : ''}. Stats: Total=${total > 1000 ? `${(total/1000).toFixed(1)}K` : total}, Avg=${avg.toFixed(1)}, Range=${min}-${max}`;
    }
    
    return `${summary}${data.length > 5 ? ` ... and ${data.length - 5} more items` : ''}`;
  }

  /**
   * Parse AI response to extract insights
   */
  private parseAIResponse(response: string): AIInsight[] {
    try {
      // Extract JSON from response (AI might include extra text)
      const jsonMatch = response.match(/\[[\s\S]*\]/);
      if (!jsonMatch) {
        throw new Error('No JSON found in AI response');
      }

      const insights = JSON.parse(jsonMatch[0]);
      
      // Validate and clean insights
      return insights
        .filter((insight: any) => insight.title && insight.description)
        .map((insight: any, index: number) => ({
          id: insight.id || `ai_insight_${Date.now()}_${index}`,
          type: insight.type || 'summary',
          title: insight.title,
          description: insight.description,
          value: insight.value,
          confidence: insight.confidence || 'medium',
          recommendation: insight.recommendation,
          priority: insight.priority || 'medium'
        }))
        .slice(0, 8); // Limit to 8 insights

    } catch (error) {
      console.warn('Failed to parse AI response:', error);
      return [];
    }
  }

  /**
   * Fallback insights when AI is not available
   */
  private generateFallbackInsights(dashboardData: DashboardData): AIInsight[] {
    const { visualizations, metadata } = dashboardData;
    
    return [
      {
        id: 'fallback_1',
        type: 'summary',
        title: 'Dashboard Overview',
        description: `This dashboard contains ${metadata.totalVisualizations} visualizations providing insights into your data.`,
        confidence: 'high',
        recommendation: 'Consider connecting to an AI service for more detailed insights.',
        priority: 'low'
      },
      ...visualizations.slice(0, 3).map((viz, index) => ({
        id: `fallback_viz_${index}`,
        type: 'summary' as const,
        title: `${viz.title} Analysis`,
        description: `${viz.title} shows ${viz.data?.length || 0} data points. This ${viz.type} visualization provides valuable insights into your metrics.`,
        value: viz.data?.length?.toString(),
        confidence: 'medium' as const,
        recommendation: 'Review the data trends and consider additional analysis.',
        priority: 'medium' as const
      }))
    ];
  }
}

export default new AIInsightsService();
export type { AIInsight, DashboardData };